language: python

sudo: false

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pytest-cov
  - pip install codecov

script:
  - python -m pytest --cov=decmath

after_success:
  - codecov
